from .db_dependency import get_cassandra_repository
from .service_dependency import get_course_service, get_student_service, get_user_service
from .message_broker_dependency import get_kafka_repository