import os
from dotenv import load_dotenv
env = os.getenv('ENV', 'development')

if env == 'development':
    load_dotenv('.env.local')
else:
    load_dotenv('.env.prod')


CASSANDRA_HOST = os.getenv('CASSANDRA_HOST')
CASSANDRA_KEYSPACE = os.getenv('CASSANDRA_KEYSPACE')
REDIS_HOST = os.getenv('REDIS_HOST')
REDIS_PORT = os.getenv('REDIS_PORT')
SOLR_URL = os.getenv('SOLR_URL')
JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY')
JWT_ALGORITHM = os.getenv('JWT_ALGORITHM')
ACCESS_TOKEN_EXPIRE_MINUTES = os.getenv('ACCESS_TOKEN_EXPIRE_MINUTES')
INTERNAL_TOKEN = os.getenv('INTERNAL_TOKEN')
NEO4J_HOST = os.getenv('NEO4J_HOST')
NEO4J_USER = os.getenv('NEO4J_USER')
NEO4J_PASSWORD = os.getenv('NEO4J_PASSWORD')
KAFKA_HOST = os.getenv('KAFKA_HOST')
KAFKA_GROUP_ID = os.getenv('KAFKA_GROUP_ID')
KAFKA_AUTO_OFFSET_RESET = os.getenv('KAFKA_AUTO_OFFSET_RESET')
MONGO_HOST = os.getenv('MONGO_HOST')
MONGO_DB = os.getenv('MONGO_DB')



configuration = {
    "CASSANDRA_HOST": CASSANDRA_HOST,
    "CASSANDRA_KEYSPACE": CASSANDRA_KEYSPACE,
    "REDIS_HOST": REDIS_HOST,
    "REDIS_PORT": REDIS_PORT,
    "SOLR_URL": SOLR_URL,
    "JWT_SECRET_KEY": JWT_SECRET_KEY,
    "JWT_ALGORITHM": JWT_ALGORITHM,
    "ACCESS_TOKEN_EXPIRE_MINUTES": ACCESS_TOKEN_EXPIRE_MINUTES,
    "INTERNAL_TOKEN": INTERNAL_TOKEN,
    "NEO4J_HOST": NEO4J_HOST,
    "NEO4J_USER": NEO4J_USER,
    "NEO4J_PASSWORD": NEO4J_PASSWORD,
    "KAFKA_HOST": KAFKA_HOST,
    "KAFKA_GROUP_ID": KAFKA_GROUP_ID,
    "KAFKA_AUTO_OFFSET_RESET": KAFKA_AUTO_OFFSET_RESET,
    "MONGO_HOST": MONGO_HOST,
    "MONGO_DB": MONGO_DB
}